# Generated by Django 2.1.7 on 2019-05-02 23:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_text_1',
            field=wagtail.core.fields.RichTextField(default='에브리데이 리무진에 오신걸 환영합니다'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_text_2',
            field=wagtail.core.fields.RichTextField(default='20년 경력의'),
        ),
    ]
