# Generated by Django 2.1.7 on 2019-05-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190502_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_text_1',
            field=models.TextField(default='에브리데이 리무진에 오신걸 환영합니다'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page_text_2',
            field=models.TextField(default='20년 경력의'),
        ),
    ]
